

/**
* @file dds_impl.c
* @brief DDS Implementation - Pure DDS Operations
* 
* Implements pure DDS functionality for entity creation, management, and data operations.
* No AUTOSAR dependencies - uses only standard DDS Micro APIs.
* 
* Configuration loaded from dds_system.xml. Type support generated by rtiddsgen from IDL.
* 
*/

#include <string.h>

#include "rti_me_c.h"

#include "wh_sm/wh_sm_history.h"
#include "rh_sm/rh_sm_history.h"
#include "disc_dpde/disc_dpde_discovery_plugin.h"
#include "netio/netio_common.h"
#include "netio/netio_udp.h"
#include "osapi/osapi_system.h"
#include "rti_me_psl/ospsl/ospsl_os_autosar_log.h"

#include <ctype.h>

#include "dds_impl.h"

/*==============================================================================
*                            TYPE SUPPORT INCLUDES
*============================================================================*/

/**
* @note TODO: Modify to include your application-specific type support code if needed
* 
* These headers are generated by rtiddsgen from your IDL or XML file:
* ```
* rtiddsgen -language C -micro -create typefiles <dds_system.idl or .xml>
* ```
* 
* Replace exampleType with your actual data type name.
*/
#include "../dds_gen/dds_system_types.h"
#include "../dds_gen/dds_system_typesSupport.h"
#include "../dds_gen/dds_system_typesPlugin.h"

/*==============================================================================
*                            APPLICATION GENERATION
*============================================================================*/

/**
* Application Generation plugin provides XML-based configuration.
* These headers are provided by RTI DDS Micro and should not be modified.
*/
#include "app_gen/app_gen.h"
#include "app_gen/app_gen_plugin.h"

/*==============================================================================
*                            STATIC VARIABLES
*============================================================================*/

/**
* @brief struct containing DDS DomainParticipant
* 
* Represents this application's connection to the DDS domain. Created by
* DdsImpl_CreateEntities() and persists for application lifetime. Must be enabled
* explicitly via DdsImpl_EnableEntities() before communication can begin.
*/
RTI_PRIVATE struct Application *DdsImpl_fv_Application = NULL;

int DdsImpl_CreateEntities()
{
    DDS_DomainParticipantFactory *factory = NULL;

    RT_Registry_T *registry = NULL;
    struct APPGEN_FactoryProperty model_xml = APPGEN_FactoryProperty_INITIALIZER;
    char *participant_name = NULL;

#if (OSAPI_ENABLE_LOG == 1 && OSAPI_ENABLE_TRACE == 1)
    /* Configure RTI DDS Micro logging */
    OSAPI_Log_set_verbosity(OSAPI_LOG_VERBOSITY_ERROR);
#endif

    OSAPI_Heap_allocate_buffer(
            (char **)&DdsImpl_fv_Application,
            sizeof(struct Application),
            OSAPI_ALIGNMENT_DEFAULT);
    if (DdsImpl_fv_Application == NULL)
    {
        AUTOSAR_LOG_DDS_APPLICATION_ALLOCATION_FAILED(
                OSAPI_LOGKIND_ERROR)
                return -1;
    }

    /* Retrieve Domain Participant Factory and registry */
    factory = DDS_DomainParticipantFactory_get_instance();
    registry = DDS_DomainParticipantFactory_get_registry(factory);

    /* Register Appgen */
    model_xml._model = APPGEN_get_library_seq();
    if (!APPGEN_Factory_register(registry, &model_xml))
    {
        AUTOSAR_LOG_DDS_APPGEN_REGISTER_FAILED(
                OSAPI_LOGKIND_ERROR)
                return -1;
    }

    /* Create participant from XML profile */
    participant_name = "parlib::PDIO_FL_Domain_6";
    DdsImpl_fv_Application->PDIO_FL_Domain_6 =
    DDS_DomainParticipantFactory_create_participant_from_config(
            factory,
            participant_name);

    if (DdsImpl_fv_Application->PDIO_FL_Domain_6 == NULL)
    {
        AUTOSAR_LOG_DDS_PARTICIPANT_CREATE_FAILED(
                OSAPI_LOGKIND_ERROR, participant_name)
                return -1;
    }

    return 0;
}

int DdsImpl_EnableEntities(void)
{
    DDS_ReturnCode_t retcode;
    if (DdsImpl_fv_Application == NULL) {
        AUTOSAR_LOG_DDS_APPLICATION_UNAVAILABLE(OSAPI_LOGKIND_ERROR)
        return -1;
    }
    retcode = DDS_Entity_enable(DDS_DomainParticipant_as_entity(DdsImpl_fv_Application->PDIO_FL_Domain_6));
    if (retcode != DDS_RETCODE_OK) {
        AUTOSAR_LOG_DDS_PARTICIPANT_ENABLE_FAILED(
                OSAPI_LOGKIND_ERROR,
                "parlib::PDIO_FL_Domain_6",
                retcode)
                return -1;
    }

    return 0;
}

int DdsImpl_Cabin_Door_PDIO_FL_WriteSample(const dds_Cabin_Door_PDIO_FL_t* dds_sample)
{
    DDS_ReturnCode_t retcode;
    DDS_DataWriter *datawriter_untyped = NULL;
    static dds_Cabin_Door_PDIO_FL_tDataWriter *datawriter = NULL;
    const char *datawriter_name = "P_PDIO_FL::Cabin_Door_PDIO_FL_Writer";

    if (dds_sample == NULL)
    {
        return -1;
    }

    datawriter_untyped = DDS_DomainParticipant_lookup_datawriter_by_name(
            DdsImpl_fv_Application->PDIO_FL_Domain_6,
            datawriter_name);
    if (datawriter_untyped == NULL)
    {
        AUTOSAR_LOG_DDS_ENDPOINT_RESOLVE_FAILED(
                OSAPI_LOGKIND_ERROR, datawriter_name)
                return -1;
    }
    datawriter = dds_Cabin_Door_PDIO_FL_tDataWriter_narrow(datawriter_untyped);
    if (datawriter == NULL)
    {
        AUTOSAR_LOG_DDS_ENDPOINT_RESOLVE_FAILED(
                OSAPI_LOGKIND_ERROR, datawriter_name)
                return -1;
    }

    /* Write sample to DDS DataWriter */
    retcode = dds_Cabin_Door_PDIO_FL_tDataWriter_write(
            datawriter,
            dds_sample,
            &DDS_HANDLE_NIL);

    if (retcode != DDS_RETCODE_OK)
    {
        AUTOSAR_LOG_DDS_WRITE_SAMPLE_FAILED(
                OSAPI_LOGKIND_ERROR, "Cabin_Door_PDIO_FL", retcode)
                return -1;
    }

    return 0;
}

int DdsImpl_GCS_LEFT_2_PDIO_FL_TakeNextSample(dds_GCS_LEFT_2_PDIO_FL_t* dds_sample, int* is_valid)
{
    DDS_ReturnCode_t retcode;
    struct DDS_SampleInfo sample_info = DDS_SampleInfo_INITIALIZER;
    DDS_DataReader *datareader_untyped = NULL;
    static dds_GCS_LEFT_2_PDIO_FL_tDataReader *datareader = NULL;
    const char *datareader_name = "S_PDIO_FL::GCS_LEFT_2_PDIO_FL_Reader";

    if (dds_sample == NULL || is_valid == NULL)
    {
        return -1;
    }

    datareader_untyped = DDS_DomainParticipant_lookup_datareader_by_name(
            DdsImpl_fv_Application->PDIO_FL_Domain_6,
            datareader_name);
    if (datareader_untyped == NULL)
    {
        AUTOSAR_LOG_DDS_ENDPOINT_RESOLVE_FAILED(
                OSAPI_LOGKIND_ERROR, datareader_name)
                return -1;
    }

    datareader = dds_GCS_LEFT_2_PDIO_FL_tDataReader_narrow(datareader_untyped);
    if (datareader == NULL)
    {
        AUTOSAR_LOG_DDS_ENDPOINT_RESOLVE_FAILED(
                OSAPI_LOGKIND_ERROR, datareader_name)
                return -1;
    }

    *is_valid = 0;

    /* Take next sample from DataReader */
    retcode = dds_GCS_LEFT_2_PDIO_FL_tDataReader_take_next_sample(
            datareader,
            dds_sample,
            &sample_info);

    if (retcode == DDS_RETCODE_NO_DATA)
    {
        /* No data available - not an error */
        return 0;
    }

    if (retcode != DDS_RETCODE_OK)
    {
        AUTOSAR_LOG_DDS_TAKE_SAMPLE_FAILED(
                OSAPI_LOGKIND_ERROR, "GCS_LEFT_2_PDIO_FL", retcode)
                return -1;
    }

    /* Check if the sample contains valid data */
    if (sample_info.valid_data)
    {
        *is_valid = 1;
    }

    return 0;
}

