

/**
* @file dds_impl.h
* @brief DDS Implementation Layer Interface (Layer 3)
* 
* This file provides the pure DDS implementation interface isolated from AUTOSAR concerns.
* It handles DDS entity creation, configuration, and data transfer operations.
* 
* @details
* **Architecture**: Layer 3 of the DDS CDD three-layer architecture
* - Layer 1: RTE Template (DdsCdd.c) - AUTOSAR runnables (integrator implements)
* - Layer 2: Adapter (dds_cdd_adapter.c) - AUTOSAR/DDS bridge
* - Layer 3: DDS Implementation (dds_impl.c) - Pure DDS operations
* 
* **Responsibilities**:
* - Create and manage DDS entities (DomainParticipant, Topics, DataWriters, DataReaders)
* - Load configuration from dds_system.xml via Application Generation plugin
* - Provide read/write operations for data transfer
* - Expose entity handles for adapter layer access
* 
* **Configuration**:
* - All DDS entities are configured via dds_system.xml
* - QoS profiles defined in XML are automatically applied
* - Entity names must match XML configuration
* - Type support generated by rtiddsgen from IDL
* 
* @note This layer has no AUTOSAR dependencies and could be reused in non-AUTOSAR contexts.
*/

#ifndef DDS_IMPL_H
#define DDS_IMPL_H

#include "../dds_gen/dds_system_types.h"  /* DDS type definition generated from IDL */

struct Application
{
    DDS_DomainParticipant *PDIO_FL_Domain_6;
};

/**
* @brief Create DDS DomainParticipant and child entities
* 
* Creates DomainParticipant from XML configuration in DISABLED state.
* Entities must be explicitly enabled via DdsImpl_EnableEntities().
* 
* @return 0 on success, -1 on error
* 
* @pre System properties must be set, dds_system.xml must be valid
* @post DomainParticipant created but disabled
*/
int DdsImpl_CreateEntities(void);

/**
* @brief Enable DDS entities for communication
* 
* Enables DomainParticipant which transitively enables all child entities.
* DDS communication can begin after this call.
* 
* @return 0 on success, -1 on error
* 
* @pre DdsImpl_CreateEntities() must have completed successfully
* @post DDS communication active
*/
int DdsImpl_EnableEntities(void);

/**
* @brief Write Cabin_Door_PDIO_FL sample to DDS DataWriter
*
* This function writes an Cabin_Door_PDIO_FL sample to the DDS DataWriter.
* It handles only DDS-specific operations.
*
* @param[in] dds_sample Pointer to dds_Cabin_Door_PDIO_FL_t structure containing data to write
* @return 0 on success, -1 on error
*/
int DdsImpl_Cabin_Door_PDIO_FL_WriteSample(const dds_Cabin_Door_PDIO_FL_t* dds_sample);

/**
* @brief Take next GCS_LEFT_2_PDIO_FL sample from DDS DataReader
*
* This function takes the next available GCS_LEFT_2_PDIO_FL sample from the DDS DataReader
* using the take_next_sample API. It handles only DDS-specific operations.
*
* @param[out] dds_sample Pointer to dds_GCS_LEFT_2_PDIO_FL_t structure to receive DDS data
* @param[out] is_valid Set to 1 if valid data received, 0 if no data or invalid
* @return 0 on success (data available or no data), -1 on error
*/
int DdsImpl_GCS_LEFT_2_PDIO_FL_TakeNextSample(dds_GCS_LEFT_2_PDIO_FL_t* dds_sample, int* is_valid);

#endif // DDS_IMPL_H