

/**
* @file dds_impl.c
* @brief DDS Implementation - Pure DDS Operations
* 
* Implements pure DDS functionality for entity creation, management, and data operations.
* No AUTOSAR dependencies - uses only standard DDS Micro APIs.
* 
* Configuration loaded from dds_system.xml. Type support generated by rtiddsgen from IDL.
* 
*/

#include <string.h>

#include "rti_me_c.h"

#include "wh_sm/wh_sm_history.h"
#include "rh_sm/rh_sm_history.h"
#include "disc_dpde/disc_dpde_discovery_plugin.h"
#include "netio/netio_common.h"
#include "netio/netio_udp.h"
#include "osapi/osapi_system.h"

#include <ctype.h>

#include "dds_impl.h"

/*==============================================================================
*                            TYPE SUPPORT INCLUDES
*============================================================================*/

/**
* @note TODO: Modify to include your application-specific type support code if needed
* 
* These headers are generated by rtiddsgen from your IDL or XML file:
* ```
* rtiddsgen -language C -micro -create typefiles <dds_system.idl or .xml>
* ```
* 
* Replace exampleType with your actual data type name.
*/
#include "../dds_gen/dds_system_types.h"
#include "../dds_gen/dds_system_typesSupport.h"
#include "../dds_gen/dds_system_typesPlugin.h"

/*==============================================================================
*                            APPLICATION GENERATION
*============================================================================*/

/**
* Application Generation plugin provides XML-based configuration.
* These headers are provided by RTI DDS Micro and should not be modified.
*/
#include "app_gen/app_gen.h"
#include "app_gen/app_gen_plugin.h"

/*==============================================================================
*                            STATIC VARIABLES
*============================================================================*/

/**
* @brief struct containing DDS DomainParticipant
* 
* Represents this application's connection to the DDS domain. Created by
* DdsImpl_CreateEntities() and persists for application lifetime. Must be enabled
* explicitly via DdsImpl_EnableEntities() before communication can begin.
*/
static struct Application *application = NULL;

#if (OSAPI_ENABLE_LOG == 1 && OSAPI_ENABLE_TRACE == 1)
/**
* @brief Custom log write function for RTI DDS Micro logging
* 
* Routes DDS log messages through printf for output.
* 
* @param buffer Log message buffer
* @param length Length of the message
*/
void my_log_write_function(const char* buffer, RTI_SIZE_T length) {
    printf("%s\n", buffer);
}
#endif

int DdsImpl_CreateEntities()
{
    DDS_DomainParticipantFactory *factory = NULL;

    RT_Registry_T *registry = NULL;
    struct APPGEN_FactoryProperty model_xml = APPGEN_FactoryProperty_INITIALIZER;
    char *participant_name = NULL;

#if (OSAPI_ENABLE_LOG == 1 && OSAPI_ENABLE_TRACE == 1)
    /* Configure RTI DDS Micro logging */
    struct OSAPI_LogProperty property;
    OSAPI_Log_get_property(&property);
    property.write_buffer = my_log_write_function;
    OSAPI_Log_set_verbosity(OSAPI_LOG_VERBOSITY_SILENT);
    if (!OSAPI_Log_set_property(&property)) {
        printf("Failed to set log property\n");
    }
#endif

    OSAPI_Heap_allocate_buffer(
            (char **)&application,
            sizeof(struct Application),
            OSAPI_ALIGNMENT_DEFAULT);
    if (application == NULL)
    {
        printf("failed to allocate application\n");
        return -1;
    }

    /* Retrieve Domain Participant Factory and registry */
    factory = DDS_DomainParticipantFactory_get_instance();
    registry = DDS_DomainParticipantFactory_get_registry(factory);

    /* Register Appgen */
    model_xml._model = APPGEN_get_library_seq();
    if (!APPGEN_Factory_register(registry, &model_xml))
    {
        printf("DdsImpl_CreateEntities: failed to register Application Generation\n");
        return -1;
    }

    /* Create participant from XML profile */
    participant_name = "parlib::PDIO_FL_Domain_6";
    application->PDIO_FL_Domain_6 =
    DDS_DomainParticipantFactory_create_participant_from_config(
            factory,
            participant_name);

    if (application->PDIO_FL_Domain_6 == NULL)
    {
        printf("DdsImpl_CreateEntities: failed to create participant %s\n",
        participant_name);
        return -1;
    }

    return 0;
}

int DdsImpl_EnableEntities(void)
{
    DDS_ReturnCode_t retcode;
    if (application == NULL) {
        printf("DdsImpl_EnableEntities: application is NULL\n");      
        return -1;
    }
    retcode = DDS_Entity_enable(DDS_DomainParticipant_as_entity(application->PDIO_FL_Domain_6));
    if (retcode != DDS_RETCODE_OK) {
        printf("DdsImpl_EnableEntities: Failed to enable participant "
        "parlib::PDIO_FL_Domain_6\n");
        return -1;
    }

    return 0;
}

int DdsImpl_Cabin_Door_PDIO_FL_WriteSample(const dds_Cabin_Door_PDIO_FL_t* dds_sample)
{
    DDS_ReturnCode_t retcode;
    DDS_DataWriter *datawriter_untyped = NULL;
    static dds_Cabin_Door_PDIO_FL_tDataWriter *datawriter = NULL;
    const char *datawriter_name = "P_PDIO_FL::Cabin_Door_PDIO_FL_Writer";

    if (dds_sample == NULL)
    {
        return -1;
    }

    datawriter_untyped = DDS_DomainParticipant_lookup_datawriter_by_name(
            application->PDIO_FL_Domain_6,
            datawriter_name);
    if (datawriter_untyped == NULL)
    {
        printf("DdsImpl_Cabin_Door_PDIO_FL_WriteSample: datawriter_untyped == NULL\n");
        return -1;
    }
    datawriter = dds_Cabin_Door_PDIO_FL_tDataWriter_narrow(datawriter_untyped);
    if (datawriter == NULL)
    {
        printf("DdsImpl_Cabin_Door_PDIO_FL_WriteSample: datawriter == NULL\n");
        return -1;
    }

    /* Write sample to DDS DataWriter */
    retcode = dds_Cabin_Door_PDIO_FL_tDataWriter_write(
            datawriter,
            dds_sample,
            &DDS_HANDLE_NIL);

    if (retcode != DDS_RETCODE_OK)
    {
        printf("DdsImpl_Cabin_Door_PDIO_FL_WriteSample: Failed to write sample, retcode(%d)\n", retcode);
        return -1;
    }

    return 0;
}

int DdsImpl_GCS_LEFT_2_PDIO_FL_TakeNextSample(dds_GCS_LEFT_2_PDIO_FL_t* dds_sample, int* is_valid)
{
    DDS_ReturnCode_t retcode;
    struct DDS_SampleInfo sample_info = DDS_SampleInfo_INITIALIZER;
    DDS_DataReader *datareader_untyped = NULL;
    static dds_GCS_LEFT_2_PDIO_FL_tDataReader *datareader = NULL;
    const char *datareader_name = "S_PDIO_FL::GCS_LEFT_2_PDIO_FL_Reader";

    if (dds_sample == NULL || is_valid == NULL)
    {
        return -1;
    }

    datareader_untyped = DDS_DomainParticipant_lookup_datareader_by_name(
            application->PDIO_FL_Domain_6, 
            datareader_name);
    if (datareader_untyped == NULL)
    {
        printf("DdsImpl_GCS_LEFT_2_PDIO_FL_TakeNextSample: datareader_untyped == NULL\n");
        return -1;
    }

    datareader = dds_GCS_LEFT_2_PDIO_FL_tDataReader_narrow(datareader_untyped);
    if (datareader == NULL)
    {
        printf("DdsImpl_GCS_LEFT_2_PDIO_FL_TakeNextSample: datareader == NULL\n");
        return -1;
    }

    *is_valid = 0;

    /* Take next sample from DataReader */
    retcode = dds_GCS_LEFT_2_PDIO_FL_tDataReader_take_next_sample(
            datareader,
            dds_sample,
            &sample_info);

    if (retcode == DDS_RETCODE_NO_DATA)
    {
        /* No data available - not an error */
        return 0;
    }

    if (retcode != DDS_RETCODE_OK)
    {
        printf("DdsImpl_GCS_LEFT_2_PDIO_FL_TakeNextSample: Failed to take sample, retcode(%d)\n", retcode);
        return -1;
    }

    /* Check if the sample contains valid data */
    if (sample_info.valid_data)
    {
        *is_valid = 1;
    }

    return 0;
}

